name: apnea
description: An apnea training app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.0.0+1
  intl: ^0.15.8
  flutter_animation_progress_bar: ^1.0.0
  sqflite: ^1.1.6+3
  path: ^1.6.2
  url_launcher: ^5.1.2
  audioplayers: ^0.13.1
  firebase_admob: ^0.9.0+3
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/audio/
    - assets/audio/inspire/

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/exo/Exo.ttf

    - family: Delius Unicase
      fonts:
        - asset: assets/fonts/delius_unicase/DeliusUnicase-Regular.ttf
        - asset: assets/fonts/delius_unicase/DeliusUnicase-Bold.ttf
          weight: 700
    
    - family: Libre Baskerville
      fonts:
        - asset: assets/fonts/libre_baskerville/LibreBaskerville-Regular.ttf
        - asset: assets/fonts/libre_baskerville/LibreBaskerville-Bold.ttf
          weight: 700